# Generated by Django 4.1.6 on 2023-02-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaddata', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=10)),
                ('sub', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('Des', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
