# Generated by Django 4.1.6 on 2023-02-18 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample', '0002_notes_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='uploaddata',
        ),
        migrations.AddField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notes',
            name='uploaddate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
