# Generated by Django 4.1.6 on 2023-02-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_remove_notes_uploaddata_notes_notesfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='uploaddate',
            new_name='uploaddate11',
        ),
    ]
