# Generated by Django 4.1.6 on 2023-02-18 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_rename_uploaddate_notes_uploaddate11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notesfile',
        ),
    ]
