# Generated by Django 4.1.6 on 2023-02-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_remove_notes_notesfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='Des',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='type',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='uploaddate11',
        ),
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='notefile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='subject',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='uploadingdate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='branch',
            field=models.CharField(max_length=30),
        ),
    ]
