# Generated by Django 4.1.6 on 2023-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_remove_notes_des_remove_notes_sub_remove_notes_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uploadingdate',
            field=models.CharField(max_length=30),
        ),
    ]
