# Generated by Django 4.1.6 on 2023-02-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_alter_notes_uploadingdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
