# Generated by Django 4.1.6 on 2023-03-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
