# Generated by Django 4.1.6 on 2023-03-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
