# Generated by Django 4.1.6 on 2023-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_alter_signup_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
