# Generated by Django 4.1.6 on 2023-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0016_alter_signup_contact_alter_signup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
