# Generated by Django 4.1.6 on 2023-05-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0018_alter_signup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='contact',
            field=models.CharField(max_length=30),
        ),
    ]
